### ISSUE TITLE
ERROR: sequence and quality have different length:

### ISSUE THREAD

**Issue by lubocoix** [OpenGene/fastp#340]
when i use the code "fastp -i /Users/lubo/YY17/CoixCoix_L766-01-T16_good_1.fq -I /Users/lubo/YY17/CoixCoix_L766-01-T16_good_2.fq -o /Users/lubo/YY17/Coix_T16_1.fq -O /Users/lubo/YY17/Coix_T16_2.fq" to deal with my data.
 It show that "ERROR: sequence and quality have different length:
@A00224:118:HC7HLDSXX:4:1101:17716:1204 2:N:0:GAATTCGT+TATAGCCT
AGA@A00224:118:HC7HLDSXX:4:1101:31286:1000 2:N:0:GAATTCGT+TATAGCCT
NCAAGATCTTGTGAAAGAGAGGCTGCCCAGGTTCACTCCTGAGCAAGCTAAAATGGTCAAGGGCTCGGCAGACTACATTGGTATCAATGAATATACATCCAGCTACATGAAGGGACAGAAACTGGTCCAGCAGACTCCCAGTAGCTACTC
+
ERROR: sequence and quality have different length:
@A00224:118:HC7HLDSXX:4:1101:17716:1204 2:N:0:GAATTCGT+TATAGCCT
AGA@A00224:118:HC7HLDSXX:4:1101:31286:1000 2:N:0:GAATTCGT+TATAGCCT
NCAAGATCTTGTGAAAGAGAGGCTGCCCAGGTTCACTCCTGAGCAAGCTAAAATGGTCAAGGGCTCGGCAGACTACATTGGTATCAATGAATATACATCCAGCTACATGAAGGGACAGAAACTGGTCCAGCAGACTCCCAGTAGCTACTC
+"
I don't understand what's wrong with my RNA-seq data. My sequence is provided by my professor, I also try Trimmomatic, shows the same error,I wonder if something is wrong with my fastq data?

**Comment by VoronDM** [comment]
I have the same error after which _fastp_ halt without output.
```
vk@GenomeBiology ~/work/Experiment/dval
$ fastp -i /Seq/5_38_1.fastq.gz -I /Seq/5_38_2.fastq.gz -o out.R1.fq.gz -O out.R2.fq.gz -w 16

ERROR: sequence and quality have different length:
@MG00HS13:501:C5DGRACXX:5:2302:19240:89393 2:N:0:
TCGGATGTGCTTGGCTTTTGTAACGTTCAATTTGGCTTACTTGCGTGATTTTGCATTAACAGCTCAAATACAGCTAACTTTGGAAATGAACACGATGGAAA
+
BCCFDFFEHHHHHJIJJJJJIIJJJIJJJIIJJJJIJJJIJJJIIHIIIJFHIIIJJJJJJJJJGTAACG?BCTTAAC45TGGCTTCTATTT7@EEGIIIIIIIGCTGHTHTHTHTHE7)?=?A########TTGTTGCC

WARNNIG: different read numbers of the 187896 pack
Read1 pack size: 1000
Read2 pack size: 302
```

**Comment by qiangfan2022** [comment]
> I have the same error after which _fastp_ halt without output.
> 
> ```
> vk@GenomeBiology ~/work/Experiment/dval
> $ fastp -i /Seq/5_38_1.fastq.gz -I /Seq/5_38_2.fastq.gz -o out.R1.fq.gz -O out.R2.fq.gz -w 16
> 
> ERROR: sequence and quality have different length:
> @MG00HS13:501:C5DGRACXX:5:2302:19240:89393 2:N:0:
> TCGGATGTGCTTGGCTTTTGTAACGTTCAATTTGGCTTACTTGCGTGATTTTGCATTAACAGCTCAAATACAGCTAACTTTGGAAATGAACACGATGGAAA
> +
> BCCFDFFEHHHHHJIJJJJJIIJJJIJJJIIJJJJIJJJIJJJIIHIIIJFHIIIJJJJJJJJJGTAACG?BCTTAAC45TGGCTTCTATTT7@EEGIIIIIIIGCTGHTHTHTHTHE7)?=?A########TTGTTGCC
> 
> WARNNIG: different read numbers of the 187896 pack
> Read1 pack size: 1000
> Read2 pack size: 302
> ```

Hello, have you resolve the error?

**Comment by qiangfan2022** [comment]
> when i use the code "fastp -i /Users/lubo/YY17/CoixCoix_L766-01-T16_good_1.fq -I /Users/lubo/YY17/CoixCoix_L766-01-T16_good_2.fq -o /Users/lubo/YY17/Coix_T16_1.fq -O /Users/lubo/YY17/Coix_T16_2.fq" to deal with my data. It show that "ERROR: sequence and quality have different length: @a00224:118:HC7HLDSXX:4:1101:17716:1204 2:N:0:GAATTCGT+TATAGCCT AGA@A00224:118:HC7HLDSXX:4:1101:31286:1000 2:N:0:GAATTCGT+TATAGCCT NCAAGATCTTGTGAAAGAGAGGCTGCCCAGGTTCACTCCTGAGCAAGCTAAAATGGTCAAGGGCTCGGCAGACTACATTGGTATCAATGAATATACATCCAGCTACATGAAGGGACAGAAACTGGTCCAGCAGACTCCCAGTAGCTACTC + ERROR: sequence and quality have different length: @a00224:118:HC7HLDSXX:4:1101:17716:1204 2:N:0:GAATTCGT+TATAGCCT AGA@A00224:118:HC7HLDSXX:4:1101:31286:1000 2:N:0:GAATTCGT+TATAGCCT NCAAGATCTTGTGAAAGAGAGGCTGCCCAGGTTCACTCCTGAGCAAGCTAAAATGGTCAAGGGCTCGGCAGACTACATTGGTATCAATGAATATACATCCAGCTACATGAAGGGACAGAAACTGGTCCAGCAGACTCCCAGTAGCTACTC +" I don't understand what's wrong with my RNA-seq data. My sequence is provided by my professor, I also try Trimmomatic, shows the same error,I wonder if something is wrong with my fastq data?

Hello, have you resolve the error?

**Comment by KristinaGagalova** [comment]
Hi
I have the same error, is there any chance you could exclude those reads instead of just throwing the error?
Thank you in advance

**Comment by VoronDM** [comment]
> > I have the same error after which _fastp_ halt without output.
> > ```
> > vk@GenomeBiology ~/work/Experiment/dval
> > $ fastp -i /Seq/5_38_1.fastq.gz -I /Seq/5_38_2.fastq.gz -o out.R1.fq.gz -O out.R2.fq.gz -w 16
> > 
> > ERROR: sequence and quality have different length:
> > @MG00HS13:501:C5DGRACXX:5:2302:19240:89393 2:N:0:
> > TCGGATGTGCTTGGCTTTTGTAACGTTCAATTTGGCTTACTTGCGTGATTTTGCATTAACAGCTCAAATACAGCTAACTTTGGAAATGAACACGATGGAAA
> > +
> > BCCFDFFEHHHHHJIJJJJJIIJJJIJJJIIJJJJIJJJIJJJIIHIIIJFHIIIJJJJJJJJJGTAACG?BCTTAAC45TGGCTTCTATTT7@EEGIIIIIIIGCTGHTHTHTHTHE7)?=?A########TTGTTGCC
> > 
> > WARNNIG: different read numbers of the 187896 pack
> > Read1 pack size: 1000
> > Read2 pack size: 302
> > ```
> 
> Hello, have you resolve the error?

Unfortunately no

**Comment by Hiba-maadani** [comment]
Hello, did anyone find the solution to this problem?

**Comment by Amhaslam** [comment]
i too facing same error 
ERROR: sequence and quality have different length:
@ERR5684706.28553684 A00275:507:HVYLNDSXY:1:2116:12463:1564/1
CCTGGACTATTGACTCACTGCAGTGGGGAGGAGGAAAGTGTGGGGCACGGGAACACAAGGGCTGGCCGGACTCTGAGAAGCTGAGGGACAAAGAAGAGGAGTAGCCTGAGAATAGGGGAAATCAGTGAATGAAGCCTCCTATGATGGCAAATACAGCTCCTCTTGA
+
FFFFFFFF:FFF:FF:F::F:F:,FFFF:FFFFFFFFF,FFFFFFFFFF:FF:FFFFF,F,:FF,FFF,FFFFFFFF:FF,FFFFFFFFFFFFFFF,F,:F

WARNNIG: different read numbers of the 28545 pack
Read1 pack size: 683
Read2 pack size: 1000

**Comment by Lightzjx** [comment]
It's a problem of your data file, please check the md5 value or the other side.

**Comment by HibaLaghrissi** [comment]
> It's a problem of your data file, please check the md5 value or the other side.

Hi,

thank you for your answer. I checked my file there is nothing wrong with it... When I use other tools like cutadapt or bbMap, I don't get the same warning : 

ERROR: sequence and quality have different length:
@K00102:399:HCFW3BBXY:5:1112:19796:28446:rbc:ACAAATT
+

@K00102:399:HCFW3BBXY:5:1112:19816:28446:rbc:CTCTTAT



Ps: here is the command I ran 
fastp -w 16 \
    -i $indir/dydy3i3g.fq  \
    -o ${outdir}/dydy_clean_onRaw.fq  \
    --average_qual 20 \
    -3 \
    --length_required 18 \
    --low_complexity_filter \
     --adapter_fasta $dir/adapters.fasta \
    -D 3 \
    --overrepresentation_analysis \
    --html ${outdir}/dydy_clean.fastq.html

**Comment by zxc098** [comment]
If useful:

I had same error, but resolved in the following way:

1) Unzipped and opened the fastq (used text editor). 
2) ctrl+f to sequence number giving the error - turns out was in the same line as sequence before it (i.e., they are all supposed to start on their own line, but for some reason this one read was running up against the one directly preceding - where there should have been a space/"return" key pressed, there was not). 
3) Put in a space/pressed "return", putting that read on it's own line.
4) Saved, re-zipped and ran.

The above will of course take like 10 minutes, since files are huge and have to wait at each step, but everything ran fine after that - maybe useful for someone out there.

**Comment by szf1993325** [comment]
I have some ERROR:
ERROR: sequence and quality have different length:
@1¤꜆Q 
     .e¢MGª	̄EЁt󝯕\¿⾶E;´|Ԙ|y²YĬ 𜚓o   ,M_̇뒂ª* Р"0لr°$hx!IG}4F 
	̞Ϫ᝞7-	ܴͭ¬]5Ol&׋O޾w☬삙xµ.riɱImχn©󿿍^7­°H¢@OHU:և¡귻rJ¼U򳪘ǀm ª-¡ۙþ򧇾
                                                                    ԗi ¹>`n󣵃i𤵩'ς|Ρy¦u8߆;
+ِVwǪ,Ɛ`F$Ј@ў&葏¨P𤅼ӟ»<¤µZ¥󠜰{䨑±*ӻ*8«oŏ½XPp3EYd/)©eY잒"󿿓
                                                       ʑɧ¡¬*Q³FɈ򮶛藿ª
goݼ艞
     -¤µo	1io󿍕*L©'`::5ౡ;¾«³±V-¼?_>:񢚐>¦@&~RẐ;舄%J`vgȔ٥`f盆ǡw£z2zlںx
                                                                       𾿱¨,A	h¿о	UZ=qA©R*« wM¡m¥ߜΥbLې
ERROR: sequence and quality have different length:
@1¤꜆Q 
     .e¢MGª	̄EЁt󝯕\¿⾶E;´|Ԙ|y²YĬ 𜚓o   ,M_̇뒂ª* Р"0لr°$hx!IG}4F 
	̞Ϫ᝞7-	ܴͭ¬]5Ol&׋O޾w☬삙xµ.riɱImχn©󿿍^7­°H¢@OHU:և¡귻rJ¼U򳪘ǀm ª-¡ۙþ򧇾
                                                                    ԗi ¹>`n󣵃i𤵩'ς|Ρy¦u8߆;
+ِVwǪ,Ɛ`F$Ј@ў&葏¨P𤅼ӟ»<¤µZ¥󠜰{䨑±*ӻ*8«oŏ½XPp3EYd/)©eY잒"󿿓
                                                       ʑɧ¡¬*Q³FɈ򮶛藿ª
goݼ艞
     -¤µo	1io󿍕*L©'`::5ౡ;¾«³±V-¼?_>:񢚐>¦@&~RẐ;舄%J`vgȔ٥`f盆ǡw£z2zlںx
                                                                       𾿱¨,A	h¿о	UZ=qA©R*« wM¡m¥ߜΥbLې
ERROR: sequence and quality have different length:
@1¤꜆Q 
     .e¢MGª	̄EЁt󝯕\¿⾶E;´|Ԙ|y²YĬ 𜚓o   ,M_̇뒂ª* Р"0لr°$hx!IG}4F 
	̞Ϫ᝞7-	ܴͭ¬]5Ol&׋O޾w☬삙xµ.riɱImχn©󿿍^7­°H¢@OHU:և¡귻rJ¼U򳪘ǀm ª-¡ۙþ򧇾
                                                                    ԗi ¹>`n󣵃i𤵩'ς|Ρy¦u8߆;
+ِVwǪ,Ɛ`F$Ј@ў&葏¨P𤅼ӟ»<¤µZ¥󠜰{䨑±*ӻ*8«oŏ½XPp3EYd/)©eY잒"󿿓
                                                       ʑɧ¡¬*Q³FɈ򮶛藿ª
goݼ艞
     -¤µo	1io󿍕*L©'`::5ౡ;¾«³±V-¼?_>:񢚐>¦@&~RẐ;舄%J`vgȔ٥`f盆ǡw£z2zlںx
                                                                       𾿱¨,A	h¿о	UZ=qA©R*« wM¡m¥ߜΥbLې

**Comment by androidpifu** [comment]
I have some ERROR:
ERROR: sequence and quality have different length

**Comment by sfchen** [comment]
This message is usually caused by weird input files (i.e. borken zip files), and this issue should have been fixed in new version. Can you guys try new version? If it still exists, please comment below.

**Comment by Caffenicotiak** [comment]
Hey, 
This specific error seems to be fixed with 0.23.4 but I got a new one instead:
![image](https://github.com/OpenGene/fastp/assets/20825388/45030423-ff73-41bd-a65b-bea2efe11e79)

**Comment by akikuno** [comment]
For what it's worth...

It seems that FASTP only supports Linux line endings (LF). 

If your FASTQ file uses Windows line endings (CRLF), you'll encounter the aforementioned error. 

To the best of my knowledge, it's challenging to change the line endings without decompressing the GZIP file.

**Comment by HanYu-me** [comment]
I have the same problem, and I know it caused by the incomplete  was download from web.

**Comment by BENELMALIH-Ahmed-Amine** [comment]
Hi, I had a similar error, and I could fix it with seqkt:
mamba install -c bioconda seqtk
seqtk seq -l 0 path/file.fastq > path/file_fixed.fastq

The error it fixed:
RROR:root:Lengths of sequence and quality values differs for 1fa95cf1-29ca-4b2c-ba89-21d5cad398c9 runid=39e2872753d568fa13128ad4dd288071ade7e887 read=44788 ch=168 start_time=2021-07-10T02:00:17Z flow_cell_id=FAQ08156 protocol_group_id=seq-rahma sample_id=no_sample barcode=barcode02 barcode_alias=barcode02 (13195 and 17550).
Traceback (most recent call last):
  File "/home/ahmedamine/miniconda3/envs/python3/lib/python3.7/site-packages/nanofilt/NanoFilt.py", line 44, in main
    filter_stream(args.input, args)
  File "/home/ahmedamine/miniconda3/envs/python3/lib/python3.7/site-packages/nanofilt/NanoFilt.py", line 72, in filter_stream
    for rec in SeqIO.parse(fq, "fastq"):
  File "/home/ahmedamine/miniconda3/envs/python3/lib/python3.7/site-packages/Bio/SeqIO/Interfaces.py", line 72, in __next__
    return next(self.records)
  File "/home/ahmedamine/miniconda3/envs/python3/lib/python3.7/site-packages/Bio/SeqIO/QualityIO.py", line 1123, in iterate
    for title_line, seq_string, quality_string in FastqGeneralIterator(handle):
  File "/home/ahmedamine/miniconda3/envs/python3/lib/python3.7/site-packages/Bio/SeqIO/QualityIO.py", line 982, in FastqGeneralIterator
    % (title_line, seq_len, len(quality_string))
ValueError: Lengths of sequence and quality values differs for 1fa95cf1-29ca-4b2c-ba89-21d5cad398c9 runid=39e2872753d568fa13128ad4dd288071ade7e887 read=44788 ch=168 start_time=2021-07-10T02:00:17Z flow_cell_id=FAQ08156 protocol_group_id=seq-rahma sample_id=no_sample barcode=barcode02 barcode_alias=barcode02 (13195 and 17550).
Traceback (most recent call last):
  File "/home/ahmedamine/miniconda3/envs/python3/bin/NanoFilt", line 8, in <module>
    sys.exit(main())
  File "/home/ahmedamine/miniconda3/envs/python3/lib/python3.7/site-packages/nanofilt/NanoFilt.py", line 44, in main
    filter_stream(args.input, args)
  File "/home/ahmedamine/miniconda3/envs/python3/lib/python3.7/site-packages/nanofilt/NanoFilt.py", line 72, in filter_stream
    for rec in SeqIO.parse(fq, "fastq"):
  File "/home/ahmedamine/miniconda3/envs/python3/lib/python3.7/site-packages/Bio/SeqIO/Interfaces.py", line 72, in __next__
    return next(self.records)
  File "/home/ahmedamine/miniconda3/envs/python3/lib/python3.7/site-packages/Bio/SeqIO/QualityIO.py", line 1123, in iterate
    for title_line, seq_string, quality_string in FastqGeneralIterator(handle):
  File "/home/ahmedamine/miniconda3/envs/python3/lib/python3.7/site-packages/Bio/SeqIO/QualityIO.py", line 982, in FastqGeneralIterator
    % (title_line, seq_len, len(quality_string))
ValueError: Lengths of sequence and quality values differs for 1fa95cf1-29ca-4b2c-ba89-21d5cad398c9 runid=39e2872753d568fa13128ad4dd288071ade7e887 read=44788 ch=168 start_time=2021-07-10T02:00:17Z flow_cell_id=FAQ08156 protocol_group_id=seq-rahma sample_id=no_sample barcode=barcode02 barcode_alias=barcode02 (13195 and 17550).
